name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cypress run
      uses: cypress-io/github-action@v6
      # continue-on-error: true
      
    - uses: actions/upload-artifact@v4
      if: failure()
      with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

    - name: Set failed tests output
      id: set_failed_tests
      run: |
        if [ "${{ steps.cypress_run.outcome }}" == "failure" ]; then
          echo "failed_tests=$(cat cypress/results/results.json | jq -r '.tests[] | select(.state == "failed") | .title')" >> $GITHUB_OUTPUT
          echo "failed_tests_count=$(cat cypress/results/results.json | jq -r '.tests[] | select(.state == "failed") | .title' | wc -l)" >> $GITHUB_OUTPUT
        else
          echo "failed_tests=none" >> $GITHUB_OUTPUT
          echo "failed_tests_count=0" >> $GITHUB_OUTPUT
        fi


    - name: Create issue on failure
      if: ${{ steps.set_failed_tests.outputs.failed_tests != 'none' }}
      uses: dacbd/create-issue-action@main
      with:
        token: ${{ secrets.GH_TOKEN }}
        title: Cypress test faliure - ${{ steps.set_failed_tests.outputs.failed_tests_count }} tests failed
        body: |
          The following tests failed in the workflow `${{ github.workflow }}` on commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}):
          
          ${{ steps.set_failed_tests.outputs.failed_tests }}
          
          Check the latest [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

          **Environment:** ${{ github.event_name }}  
          **Branch:** ${{ github.ref }}  
          **Commit Message:** ${{ github.event.head_commit.message }}

        #   labels: |
        #   cypress-failure
        #   automation
        #   bug  # Add any additional labels you want here
        #   ${{ steps.set_failed_tests.outputs.failed_tests }}
        #   assignees: |
        #   zartash-infini  # Replace with GitHub username
        #   # username2  # Add more usernames as needed



    - name: Upload Cypress Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: cypress/videos


















# name: CI

# on: [push]

# jobs:

#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v4
    
#     - name: Run a failing command
#       run: exit 1
      
#     - name: Create issue on failure
#       if: ${{ failure() }}
#       uses: dacbd/create-issue-action@main
#       with:
#         token: ${{ secrets.GH_TOKEN }}
#         title: Workflow failure in ${{ github.workflow }}
#         body: |
#           The workflow `${{ github.workflow }}` failed on commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}).
          
#            Job: ${{ job.job }}
#            Step: ${{ steps.stepName.outcome }}

























# name: CI

# on:
#   push:
#     branches:
#       - main
#   pull_request:

# jobs:
#   build:
#     runs-on: ubuntu-22.04

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     # - name: Install dependencies
#     #   run: npm install
      

#     - name: Cypress run
#       # run: npx cypress run --headless
#       uses: cypress-io/github-action@v6
#       # continue-on-error: true  # Continue running even if the tests fail

#     # - uses: actions/upload-artifact@v4
#     #   if: failure()
#     #   with:
#     #       name: cypress-screenshots
#     #       path: cypress/screenshots
#     #       if-no-files-found: ignore

#     - name: Create GitHub Issue on Test Failure
#       if: failure()
#       # if: always()
#       uses: actions/github-script@v6
#       with:
#         script: |
#           console.log('Running issue creation script...');
#           if (core.getInput('conclusion') === 'failure') {
#             const issues = await github.rest.issues.listForRepo({
#               owner: context.repo.owner,
#               repo: context.repo.repo,
#               labels: "cypress-failure",
#               state: "open"
#             });
#             console.log(`Found ${issues.data.length} open issues with 'cypress-failure' label.`);

#             if (issues.data.length === 0) {
#               console.log('No existing issue found, creating a new one...');
#               await github.rest.issues.create({
#                 owner: context.repo.owner,
#                 repo: context.repo.repo,
#                 title: `Cypress Test Failure in ${github.context.workflow}`,
#                 body: `A test failed in the CI pipeline.\n\nCheck the latest [workflow run](${github.context.server_url}/${github.context.repo.owner}/${github.context.repo.repo}/actions/runs/${github.run_id}) for details.`,
#                 labels: ["cypress-failure"],
#               });
#               console.log('Issue created successfully.');
#             } else {
#               console.log('Existing issue found, not creating a new one.');
#             }
#           } else {
#             console.log('No test failures detected, skipping issue creation.');
#           }
#       env:
#           GH_TOKEN: ${{ secrets.GH_TOKEN }}

#     - name: Upload Cypress Artifacts
#       if: always()
#       uses: actions/upload-artifact@v4
#       with:
#         name: cypress-videos
#         path: cypress/videos

#     - name: Upload Test Results
#       if: always()
#       uses: actions/upload-artifact@v4
#       with:
#         name: cypress-results
#         path: cypress/results

