name: End-to-end tests
on: push
 
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        # after the test run completes store videos and any screenshots
        # on the GitHub Action artifacts
      - uses: actions/upload-artifact@v4
        # add the line below to store screenshots only on failures
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
          if-no-files-found: ignore # 'warn' or 'error' are also available, defaults to `warn`
      - name: Notify Microsoft Teams
        if: always()
        run: |
          STATUS="Success"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="Failure"
          fi
          
          curl -H 'Content-Type: application/json' \
               -d '{
                     "text": "Cypress test run for `main` branch has completed.",
                     "themeColor": "0076D7",
                     "title": "Cypress Test Results: '"${STATUS}"'",
                     "sections": [
                       {
                         "activityTitle": "Test Status: '"${STATUS}"'",
                         "activitySubtitle": "Repository: ${{ github.repository }}",
                         "activityImage": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
                         "facts": [
                           {
                             "name": "Branch",
                             "value": "${{ github.ref }}"
                           },
                           {
                             "name": "Commit",
                             "value": "${{ github.sha }}"
                           },
                           {
                             "name": "Workflow",
                             "value": "${{ github.workflow }}"
                           }
                         ],
                         "markdown": true
                       }
                     ]
                   }' \
               ${TEAMS_WEBHOOK_URL}
        # env:
          # TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}