name: CI-Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: npm install
      

    - name: Cypress run
      # run: npx cypress run --headless
      uses: cypress-io/github-action@v6
      continue-on-error: true  # Continue running even if the tests fail

    - name: Create GitHub Issue on Test Failure
      # if: failure()
      if: always()
      uses: actions/github-script@v6
      with:
        script: |
          const issues = await octokit.issues.listForRepo({
            owner: context.repo.owner,
            repo: context.repo.repo,
            labels: "cypress-failure",
            state: "open"
          });

          if (issues.data.length === 0 && github.event.workflow_run.conclusion === 'failure') {
            await octokit.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Cypress Test Failure in ${context.workflow}`,
              body: `A test failed in the CI-Test pipeline.\n\nCheck the latest [workflow run](${context.payload.workflow_run.html_url}) for details.`,
              labels: ["cypress-failure"],
            });
          }}
      env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

    - name: Upload Cypress Artifacts
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-videos
        path: cypress/videos

    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: cypress-results
        path: cypress/results






# name: End-to-end tests

# on: 
#   push:
#     branches:
#       - main
#   pull_request:
#     branches:
#       - main
 
# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4
        
#       # Install npm dependencies, cache them correctly
#       # and run all Cypress tests
#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         continue-on-error: true
        
#       # Store screenshots only on failures
#       - uses: actions/upload-artifact@v4
#         if: failure()
#         with:
#           name: cypress-screenshots
#           path: cypress/screenshots
#           if-no-files-found: ignore

#       # Store videos always, even if tests pass
#       - uses: actions/upload-artifact@v4
#         if: always()
#         with:
#           name: cypress-videos
#           path: cypress/videos
#           if-no-files-found: ignore