name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  cypress-test-build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
     


    # - name: Install cypress and verify
    #   run: npm install -g cypress

    # - name: Verify cypress
    #   run: cypress verify

    # - name: Install dependencies
    #   run: npm install

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        browser: chrome
        # record: true
      continue-on-error: true
      env:
          CI: true


    - name: Clean up old reports
      run: |
            rm -rf cypress/reports/*.html
            rm -rf cypress/videos/*
            rm -rf cypress/screenshots/*


      # Generate Mocha Report
    - name: Generate Mochawesome report
      run: npm run mochaowesome:report

    - name: Upload Mochawesome report
      if: always()
      uses: actions/upload-artifact@v4
      with:
          name: cypress-report
          path: cypress/reports/mochawesome.html


    - uses: actions/upload-artifact@v4
      if: ${{ failure() }}
      with:
          name: cypress-screenshots
          path: cypress/screenshots
          if-no-files-found: ignore

    - name: Upload Cypress Artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: cypress-videos
        path: cypress/videos
        if-no-files-found: ignore


    

    # - name: Create issue on failure
    #   if: ${{ failure() }}
    #   uses: dacbd/create-issue-action@main
    #   with:
    #     token: ${{ secrets.GH_TOKEN }}
    #     title: Cypress test fail in ${{ github.workflow }}
    #     body: |
    #       The workflow `${{ github.workflow }}` failed on commit [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }}).
    #       Check the latest [workflow run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details.

    #       **Environment:** ${{ github.event_name }}  
    #       **Branch:** ${{ github.ref }}  
    #       **Commit Message:** ${{ github.event.head_commit.message }}

    #       **Screenshots:** [Download Screenshots](https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/cypress-screenshots)
    #       **Videos:** [Download Videos](https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/cypress-videos)
    #       **Mochawesome Report:** [Download Report](https://github.com/${{ github.repository }}/actions/artifacts/${{ github.run_id }}/cypress-report)
    
    - name: Create GitHub issue
      if: failure()
      uses: actions/github-script@v6
      with:
       script: |
         const { exec } = require('@actions/exec');
         const releaseUrl = `https://github.com/${{ github.repository }}/releases/tag/cypress-artifacts-${{ github.run_number }}`;
        
          const issue = await github.issues.create({
          owner: context.repo.owner,
          repo: context.repo.repo,
          title: `Test Failure in Run #${{ github.run_number }}`,
          body: `The tests in this run have failed. You can find the screenshots, videos, and reports at the following link:\n\n[Artifacts](${releaseUrl})`
         });

          console.log(`Created issue: ${issue.data.html_url}`);
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}






    - name: Push Cypress artifacts on failed
      if: ${{ failure() }}
      run: |  
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cypress/videos/ cypress/screenshots/ cypress/reports/
          git commit -m "Add Cypress artifacts from failed tests"
          git push origin HEAD:main
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


    - name: Check permissions
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/${{ github.repository }}/collaborators


    
    - name: Push Cypress artifacts on Passed
      run: |  
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add cypress/videos/ cypress/reports/
          git commit -m "Add Cypress artifacts from Passed tests"
          git push origin HEAD:main
      env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


    

    # - name: Commit & Push screenshots, videos and reports
      # run: |
      #   git config --local user.email "rashid.6689@gmail.com"  # Replace with your email
      #   git config --local user.name "rashid-infi-cicd"  # Replace with your name
        
      #   # Check if there are any screenshots to commit
      #   if [ "$(ls -A cypress/screenshots)" ]; then
      #     git add cypress/screenshots
      #   else
      #     echo "No screenshots to commit."
      #   fi

      #   # Check if there are any videos to commit
      #   if [ "$(ls -A cypress/videos)" ]; then
      #     git add cypress/videos
      #   else
      #     echo "No videos to commit."
      #   fi

      #   # Check if there are any reports to commit
      #   if [ "$(ls -A cypress/reports)" ]; then
      #     git add cypress/reports
      #   else
      #     echo "No reports to commit."
      #   fi

      #   # Commit if there are any changes
      #   if ! git diff --cached --quiet; then
      #     git commit -m "Add Cypress artifacts from CI"
      #     git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
      #     else
      #     echo "No changes to commit."
      #   fi
        
      # env:
      #   GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token for authentication






    # - name: On fails Commit & Push screenshots, videos and reports
    #   if: ${{ failure() }}
    #   run: |
    #     git config --local user.email "rashid.6689@gmail.com"  # Replace with your email
    #     git config --local user.name "rashid-infi-cicd"  # Replace with your name
        
    #     # Check if there are any screenshots to commit
    #     if [ "$(ls -A cypress/screenshots)" ]; then
    #       git add cypress/screenshots
    #     else
    #       echo "No screenshots to commit."
    #     fi

    #     # Check if there are any videos to commit
    #     if [ "$(ls -A cypress/videos)" ]; then
    #       git add cypress/videos
    #     else
    #       echo "No videos to commit."
    #     fi

    #     # Check if there are any reports to commit
    #     if [ "$(ls -A cypress/reports)" ]; then
    #       git add cypress/reports
    #     else
    #       echo "No reports to commit."
    #     fi

    #     # Commit if there are any changes
    #     if ! git diff --cached --quiet; then
    #       git commit -m "Add Cypress artifacts from CI"
    #       git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
    #       else
    #       echo "No changes to commit."
    #     fi
        
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Use the token for authentication
    
      